#!/bin/bash
# leftokill daemon
# chkconfig: 345 20 80
# description: leftokill daemon
# processname: leftokilld 

. /etc/rc.d/init.d/functions
PROG_NAME="leftokilld"
DAEMON_PATH="/usr/bin/leftokilld"
NN="$(which tr) '\n' '\0'"

case "$1" in
start)
	echo -n $"Starting $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d start)
	retval=$?
	echo $msg | eval $NN
	echo
	exit $retval
;;
stop)
	echo -n $"Stopping $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d stop)
	retval=$?
	echo $msg | eval $NN
	echo
	exit $retval
;;
restart)
	echo -n $"Restarting $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d restart)
	retval=$?
	echo $msg | eval $NN
	echo
	exit $retval
;;
status)
	echo -n $"Status $PROG_NAME: "
	msg=$(daemon $DAEMON_PATH -d status)
	retval=$?
	echo $retval
	echo $msg | eval $NN
	echo
	exit $retval
;;
*)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
esac

